[[plugins]]
repo = "reedes/vim-colors-pencil"

[[plugins]]
repo = "tomasr/molokai"

[[plugins]]
repo = "kyazdani42/nvim-web-devicons"

[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = '''
set laststatus=2
set noshowmode

let g:lightline = {
    \  'enable': { 'tabline': 1 },
    \  'colorscheme': 'default',
    \  'component_type': {
    \    'linter_warnings': 'warning',
    \    'linter_errors': 'error',
    \  },
    \  'active': {
    \    'left': [ ['mode', 'paste'], ['readonly', 'filename', 'modified'] ],
    \    'right': [
    \               ['fileencording'], 
    \               ['percent'],
    \               ['linter_checking', 'linter_errors',
    \                'linter_warnings', 'linter_infos', 'linter_ok']
    \             ] 
    \  },
    \  'inactive': {
    \    'left': [ ['filename'] ],
    \    'right': [ 
    \               ['fileencording'],
    \               ['linter_checking', 'linter_errors',
    \                'linter_warnings', 'linter_infos', 'linter_ok']
    \             ]
    \  },
    \  'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
    \  'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
    \ } 

'''

[[plugins]]
repo = "romgrk/barbar.nvim"
depends = ['nvim-web-devicons']
hook_add = '''
let bufferline = {}
let bufferline.animation = v:true
let bufferline.auto_hide = v:false
let bufferline.icons = v:true

let bufferline.icon_separator_active = '▎'
let bufferline.icon_separator_inactive = '▎'
let bufferline.icon_close_tab = '▼'
let bufferline.icon_close_tab_modified = '●'

let bufferline.closable = v:true
let bufferline.clickable = v:true
let bufferline.semantic_letters = v:true

let bufferline.letters =
  \ 'asdfjkl;ghnmxcvbziowerutyqpASDFJKLGHNMXCVBZIOWERUTYQP'
let bufferline.maximum_padding = 4
'''

[[plugins]]
repo = "dstein64/nvim-scrollview"
hook_add = '''
let g:scrollview_on_startup = 1
let g:scrollview_excluded_filetypes = ['defx']
let g:scrollview_current_only = 1
let g:scrollview_winblend = 75
let g:scrollview_base = 'buffer'
let g:scrollview_column = 80
'''
